DATA:
  ROOT: "/kaggle/input/camus-lv/camus"
  IMG_SIZE: 256
  BATCH_SIZE: 8
  NUM_WORKERS: 4
  CLASSES:
    - background
    - myo
    - lv
MODEL:
  ARCH: FPN
  ENCODER: efficientnet-b0
  ENCODER_WEIGHTS: imagenet
  # FROZEN_CKPT: "/kaggle/input/camus-lv/checkpoint_FPN_efficientnet-b0_multicls.pth"
  # RECONS_CKPT: "/kaggle/input/camus-lv/checkpoint_recons_norm_gauss.pth"
DEVICE: gpu
NUM_EPOCHS: 40
SAVE_DIR: "/kaggle/working/"
EVAL_FREQ: 4
GAMMA: 0.6
UNC_MODE: bnn
IGNORE_BG: false
EXP_NAME: frozen_model
SEED_NUM: 1