DATA:
  SPACE: "gray"
  ROOT: "./camus"
  IMG_SIZE: 256
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  CLASSES:
    - background
    - myo
    - lv
MODEL:
  ARCH: FPN
  ENCODER: resnet34
  ENCODER_WEIGHTS: imagenet
  FROZEN_CKPT: "./frozen_concat_epoch29-valid_dataset_dice0.92.ckpt"
  RECONS_CKPT: "./recons_gausscap_epoch29-valid_dice0.84.ckpt"
  RESUME_CKPT: ""
DEVICE: cuda
NUM_EPOCHS: 1
SAVE_DIR: "./outputs"
EVAL_FREQ: 2
GAMMA: 0.6
UNC_MODE: bnn
IGNORE_BG: false
USE_CONTEXT: true
EXP_NAME: tmp
SEED_NUM: 1
GPU_ID: 1
